version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha_segura
    networks:
      - app-network

networks:
  app-network:
    driver: bridge