version: '3'
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha_segura
    networks:
      - app-network

networks:
  app-network:
    driver: bridge